### ISSUE TITLE
V2.0.3P1T2 不能适配

### ISSUE THREAD

**Issue by Thanf-code** [voidxxl7/ZXHN-F650-PassReader#1]
![image](https://user-images.githubusercontent.com/82493550/118788893-d0243000-b8c6-11eb-980a-022414436eda.png)

**Comment by bcdsee** [comment]
V2.0.3P1T2 似乎不支持你的光猫，不行

**Comment by hfutxqd** [comment]
V2.0.0P1T3 似乎不支持你的光猫

**Comment by zjj3555** [comment]
同上2.0.3不支持

**Comment by voidxxl7** [comment]
更新了，理论上应该支持了(当然我没有环境去测试)

**Comment by myyng7510** [comment]
新版还是不支持：设备类型：GPON天翼网关(4口单频)
设备型号：ZXHN F650
固件版本：V2.0.0P1T3
-----------------------------------------
panic: panic called with nil argument

goroutine 1 [running]:
main.(*F650).DownConfig(0xc00004e050?)
        /public/ZXHN-F650-PassReader/main.go:211 +0x154
main.main()
        /public/ZXHN-F650-PassReader/main.go:113 +0x3ba
