### ISSUE TITLE
V2.0.0P1T3版本错误

### ISSUE THREAD

**Issue by weirb02** [voidxxl7/ZXHN-F650-PassReader#7]
```
登录成功
-----------------------------------------
设备类型：GPON天翼网关(4口单频)
设备型号：ZXHN F650
固件版本：V2.0.0P1T3
-----------------------------------------
panic: panic called with nil argument

goroutine 1 [running]:
main.(*F650).DownConfig(0xc000104000?)
        /public/ZXHN-F650-PassReader/main.go:211 +0x154
main.main()
        /public/ZXHN-F650-PassReader/main.go:113 +0x3ba
```

同型号设备之前可以用此程序获取超级密码，后来光猫后台升级系统后报上面错误，求大佬帮助

**Comment by allfuck** [comment]
报楼上一样的错
以前破解出了密码，最近想登录试一下，发现不能登录了，重定向到useradmin,
应该后台升级过了，

**Comment by sorker** [comment]
一样的错误，据说是换了动态密码了

**Comment by allfuck** [comment]
> 一样的错误，据说是换了动态密码了

是的，我问 负责片区的装机工程师让他 问他们电信内部打电话去要的密码，看上去就是一串动态生成的密码，拿到密码后能登录，一分钟不动 自动就退出了，不知道是我自己点了一下保存还是什么，退出后就不能再登录了，提示密码错误。浙江电信应该是不想让大家改设置，像tr069 不让改动的，网上说的方法是很早以前的，压根没用。

**Comment by sorker** [comment]
你拿到临时密码和后打开telnet，这样是不是以后就可以用命令拿到密码了

> > 一样的错误，据说是换了动态密码了
> 
> 是的，我问 负责片区的装机工程师让他 问他们电信内部打电话去要的密码，看上去就是一串动态生成的密码，拿到密码后能登录，一分钟不动 自动就退出了，不知道是我自己点了一下保存还是什么，退出后就不能再登录了，提示密码错误。浙江电信应该是不想让大家改设置，像tr069 不让改动的，网上说的方法是很早以前的，压根没用。

**Comment by ku891** [comment]
配置文件db_user_cfg.xml, 替换/userconfig/cfg/db_user_cfg.xml 文件. 
**********
<DM name="SupportCertAuth" val="0"/>
<DM name="Tr069Enable" val="1"/> ******把这个参数值1改为0, 重启就不下发新的密码了.
<DM name="MWSURL" val="http://0.0.0.0:9090"/>
*************

**Comment by ku891** [comment]
`<DM name="SupportCertAuth" val="0"/>
<DM name="Tr069Enable" val="1"/> ******把这个参数值1改为0, 重启就不下发新的密码了. *************
<DM name="MWSURL" val="http://0.0.0.0:9090"/>`

**Comment by fbicewind** [comment]
> 配置文件db_user_cfg.xml, 替换/userconfig/cfg/db_user_cfg.xml 文件.
> 
> ******把这个参数值1改为0, 重启就不下发新的密码了. *************

这个文件在哪里
