### ISSUE TITLE
V2.0.0P1T2 这个版本没有成功

### ISSUE THREAD

**Issue by kknd222** [voidxxl7/ZXHN-F650-PassReader#8]
登录成功
-----------------------------------------
设备类型：GPON天翼网关(4口单频)
设备型号：ZXHN F650
固件版本：V2.0.0P1T2
-----------------------------------------
panic: panic called with nil argument

goroutine 1 [running]:
main.(*F650).DownConfig(0xc00006a050?)
        /public/ZXHN-F650-PassReader/main.go:211 +0x154
main.main()
        /public/ZXHN-F650-PassReader/main.go:113 +0x3ba
报这个错
我用网上的fiddler下断的方法也没有进入的/目录下，进去是空的

**Comment by yes-github** [comment]
登录成功
-----------------------------------------
设备类型：GPON天翼网关(4口双频)
设备型号：ZXHN F650A(GPON ONU)
固件版本：V3.0.0P1T1
-----------------------------------------
panic: panic called with nil argument

goroutine 1 [running]:
main.(*F650).DownConfig(0xc0000e8000?)
        /public/ZXHN-F650-PassReader/main.go:211 +0x154
main.main()
        /public/ZXHN-F650-PassReader/main.go:113 +0x3ba

**Comment by horizon86** [comment]
我是V2.0.3P1T1，也不行，用网上复制文件的方法也失败了，复制不出来
