### ISSUE TITLE
ZXHN F650(GPON ONU)——V2.0.3P1T4

### ISSUE THREAD

**Issue by star2k** [voidxxl7/ZXHN-F650-PassReader#9]
C:\>ZXHN-F650-PassReader
用户名： useradmin
密  码： ****

登录成功
-----------------------------------------
设备类型：GPON天翼网关(4口单频)
设备型号：ZXHN F650(GPON ONU)
固件版本：V2.0.3P1T4
-----------------------------------------
panic: panic called with nil argument

goroutine 1 [running]:
main.(*F650).DownConfig(0xc00005c050?)
        /public/ZXHN-F650-PassReader/main.go:211 +0x154
main.main()
        /public/ZXHN-F650-PassReader/main.go:113 +0x3ba

cmd下也无法查看！

**Comment by Ulysses41** [comment]
+1

**Comment by halfu** [comment]
同样的问题，求更新。
